CREATE TABLE IF NOT EXISTS cdm.dm_courier_ledger (
	id int NOT NULL GENERATED ALWAYS AS IDENTITY,
	courier_id varchar(255) NOT NULL,
	courier_name varchar(100) NOT NULL,
	settlement_year smallint NOT NULL,
	settlement_month smallint NOT NULL,
	orders_count int NOT NULL DEFAULT 0,
	orders_total_sum numeric(14, 2) NOT NULL DEFAULT 0,
	rate_avg numeric(3, 2) NOT NULL DEFAULT 0,
	order_processing_fee numeric(14, 2) NOT NULL DEFAULT 0,
	courier_order_sum numeric(14, 2) NOT NULL DEFAULT 0,
	courier_tips_sum numeric(14, 2) NOT NULL DEFAULT 0,
	courier_reward_sum numeric(14, 2) NOT NULL DEFAULT 0,
	CONSTRAINT dm_courier_ledger_courier_order_sum_check CHECK (courier_order_sum >= 0),
	CONSTRAINT dm_courier_ledger_courier_reward_sum_check CHECK (courier_reward_sum >= 0),
	CONSTRAINT dm_courier_ledger_courier_tips_sum_check CHECK (courier_tips_sum >= 0),
	CONSTRAINT dm_courier_ledger_order_processing_fee_check CHECK (order_processing_fee >= 0),
	CONSTRAINT dm_courier_ledger_orders_count_check CHECK (orders_count >= 0),
	CONSTRAINT dm_courier_ledger_orders_total_sum_check CHECK (orders_total_sum >= 0),
	CONSTRAINT dm_courier_ledger_pkey PRIMARY KEY (id),
	CONSTRAINT dm_courier_ledger_rate_avg_check CHECK (rate_avg >= 0),
	CONSTRAINT dm_courier_ledger_settlement_month_check CHECK ((settlement_month >= 1) AND (settlement_month <= 12)),
	CONSTRAINT dm_courier_ledger_settlement_year_check CHECK ((settlement_year >= 2022) AND (settlement_year < 2500)),
	CONSTRAINT dm_courier_ledger_unique_id_year_month UNIQUE (courier_id, settlement_year, settlement_month)
);